# Generated by Django 4.2.7 on 2023-11-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtable',
            name='id',
            field=models.IntegerField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
