# Generated by Django 4.2.7 on 2023-11-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtable',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookingtable',
            name='noofguests',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='menutable',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menutable',
            name='inventory',
            field=models.IntegerField(),
        ),
    ]
