# Generated by Django 4.2.7 on 2023-11-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_bookingtable_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menutable',
            name='inventory',
        ),
        migrations.AlterField(
            model_name='bookingtable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='menutable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
